#!/usr/bin/env bash

# Function to display subdomain record
display_subdomain_info() {
  domain=$1
  subdomain=$2
  ip_address=$(dig +short $subdomain.$domain)

  if [ -n "$ip_address" ]; then
    echo "The subdomain $subdomain is an A record and points to $ip_address"
  fi
}

# Check for domain argument
if [ -z "$1" ]; then
  echo "You must provide a domain name."
  exit 1
fi

# The domain argument
domain=$1

# Subdomains to check
subdomains=("www" "lb-01" "web-01" "web-02")

# Display the A record for each subdomain if no subdomain is provided
if [ -z "$2" ]; then
  for subdomain in "${subdomains[@]}"; do
    display_subdomain_info $domain $subdomain
  done
else
  # If a subdomain is provided, only display that subdomain's info
  subdomain=$2
  display_subdomain_info $domain $subdomain
fi
